### ISSUE TITLE
[1.0.1] Version File not modified

### ISSUE THREAD

**Issue by kretze** [FirstPersonKSP/RasterPropMonitor#146] opened 2024-09-16 11:18 UTC
Version 1.0.1
Install with ckan
KSP AVC still reports that it is version 0.31.13.4

Infos from ckan
![image](https://github.com/user-attachments/assets/dfeedca6-cc5f-4741-bed6-02decc0233d2)

![image](https://github.com/user-attachments/assets/b9f57661-ffae-4a46-8dee-2ad5e868bc38)

**Comment by HebaruSan** [comment] 2024-09-17 02:21
Probably fixed by KSP-CKAN/NetKAN#10217 and https://github.com/KSP-CKAN/CKAN-meta/commit/60141bfd22e57216f90316a1208f4c768ab6b0cf

**Comment by JonnyOThan** [comment] 2024-09-17 04:11
I can't repro this, but it could have conceivably been caused by dropping the `v` on the version number when I switched to using KSPBuildTools.  That was fixed here: https://github.com/KSP-CKAN/NetKAN/pull/10217. @kretze can you try to reproduce this problem again?  And if so, please include detailed repro steps starting from a vanilla install.

**Comment by JonnyOThan** [comment] 2024-09-17 04:32
OK I thought I had a lead on a repro but really I just have 0.31.13.4 installed.  Then I looked closer at the version info in the OP: RasterPropMonitor has been updated to 1.0.1 but RasterPropMonitor-Core has not.  This should now be fixed with the metadata update.

**Closed** 2024-09-17 04:34 UTC
